class Typewriter{constructor(a){Typewriter.instanceCounter=(Typewriter.instanceCounter||0)+1,this.instanceId=Typewriter.instanceCounter;const{hTag:b,addClass:c,textArray:d,targetParent:e,randomText:g=!1,caretFrequency:h=1e3,endHold:i=2e3,startHold:j=500,characterHold:k=200,deleteHold:l=100,caretClass:f}=a;this.options={hTag:b,addClass:c,textArray:d,targetParent:e,randomText:g,caretFrequency:h,endHold:i,startHold:j,characterHold:k,deleteHold:l,caretClass:f},this.loopNum=0,this.isDeleting=!1,this.txt="",this.currentText="",this.previousTextIndex=-1,this._init=this._init.bind(this),"loading"===document.readyState?document.addEventListener("DOMContentLoaded",this._init):this._init()}_init(){const{hTag:a,addClass:b,textArray:c,targetParent:d,randomText:e,caretFrequency:f,endHold:g,startHold:h,characterHold:i,deleteHold:j,caretClass:k}=this.options;if(!b)throw new Error("Typewriter Error: 'addClass' is required.");if(!d)throw new Error("Typewriter Error: 'targetParent' is required.");if(!c||!Array.isArray(c)||0===c.length)throw new Error("Typewriter Error: 'textArray' must be a non-empty array.");if(this.hTag=/^h[1-6]$/.test(a)?a:"h1",this.addClass=b,this.textArray=c.slice(),this.targetParent=document.getElementById(d),!this.targetParent)throw new Error(`Typewriter Error: No element found with id '${d}'.`);this.randomText=e,this.caretFrequency=f,this.endHold=g,this.startHold=h,this.characterHold=i,this.deleteHold=j,this.caretClass=k,this._createElements(),this.tick()}_createElements(){this.headingElement=document.createElement(this.hTag),this.headingElement.classList.add(this.addClass,"typewriter-text"),this.wrapSpan=document.createElement("span"),this.wrapSpan.classList.add("typewriter-wrap"),this.caretClass&&this.wrapSpan.classList.add(this.caretClass),this.headingElement.appendChild(this.wrapSpan),this.targetParent.appendChild(this.headingElement);const a=document.createElement("style");a.type="text/css";const b=`
    @keyframes blink-caret-${this.instanceId} {
      0%, 50% { border-right-color: #fff; }
      50.01%, 100% { border-right-color: transparent; }
    }
  `;a.innerHTML=`
    ${b}
    .typewriter-wrap {
      animation: blink-caret-${this.instanceId} ${this.caretFrequency}ms step-end infinite;
    }
  `,document.head.appendChild(a)}_getNextText(){if(this.randomText){if(1===this.textArray.length)return this.textArray[0];let a;do a=Math.floor(Math.random()*this.textArray.length);while(a===this.previousTextIndex);return this.previousTextIndex=a,this.textArray[a]}else{const a=this.loopNum%this.textArray.length;return this.textArray[a]}}tick(){this.currentText||(this.currentText=this._getNextText()),this.txt=this.isDeleting?this.currentText.substring(0,this.txt.length-1):this.currentText.substring(0,this.txt.length+1),this.wrapSpan.textContent=this.txt;let a=this.isDeleting?this.deleteHold:this.characterHold;this.isDeleting||this.txt!==this.currentText?this.isDeleting&&""===this.txt&&(this.isDeleting=!1,this.loopNum++,this.currentText="",a=this.startHold):(a=this.endHold,this.isDeleting=!0),setTimeout(()=>this.tick(),a)}}window.Typewriter=Typewriter;